"""Assert the Python sender's wire format against the TypeScript codec.

The vectors are not written down here. They are generated by
`node --import tsx tests/extract_vectors.mjs` from the same modules the browser
ships, and this file consumes that JSON. Transcribing them would mean that the
first time one failed, someone would "fix" the constant and the test would stop
measuring anything.

    npm run build:vectors && python3 -m pytest tests/test_parity.py
    (or just: python3 tests/test_parity.py)
"""

from __future__ import annotations

import gzip
import json
import os
import subprocess
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "cli"))

import qrsend  # noqa: E402

VECTORS_PATH = ROOT / "tests" / "vectors.json"


def load_vectors() -> dict:
    """Use a committed vectors.json if present, else generate it with node."""
    if VECTORS_PATH.exists():
        return json.loads(VECTORS_PATH.read_text())
    out = subprocess.run(
        ["node", "--import", "tsx", str(ROOT / "tests" / "extract_vectors.mjs")],
        cwd=ROOT, capture_output=True, text=True, check=True,
    )
    return json.loads(out.stdout)


VECTORS = load_vectors()


def fnv_hex(data: bytes) -> str:
    return f"0x{qrsend.fnv1a(data):08x}"


def test_payload(byte_length: int) -> bytes:
    """The deterministic filler the stream fingerprints were recorded against."""
    return bytes(((i * 37 + (i >> 8) * 11) & 0xFF) for i in range(byte_length))


class TestDlog(unittest.TestCase):
    def test_sweep_is_bit_exact(self):
        # Both domains soliton_cdf can reach, exhaustively. Eleven spot values
        # would miss the 0.2% of inputs a shortened series changes.
        import struct as _struct
        values = bytearray()
        for k in range(1, 65536):
            values += _struct.pack("<d", qrsend.dlog(2 * k))
        for i in range(64, 64 * 4096):
            values += _struct.pack("<d", qrsend.dlog(i / 64))
        self.assertEqual(fnv_hex(bytes(values)), VECTORS["dlogSweepFnv"])

    def test_is_not_math_log(self):
        # dlog exists precisely because it is not the platform's log. If these
        # ever agree everywhere, someone has "simplified" it back.
        import math
        differing = sum(
            1 for k in range(2, 20001)
            for x in (k, k / 0.5)
            if qrsend.dlog(x) != math.log(x)
        )
        self.assertGreater(differing, 0, "dlog became math.log — parity is now luck")


class TestSolitonCdf(unittest.TestCase):
    def test_fingerprints(self):
        import struct as _struct
        for k_str, expected in VECTORS["solitonCdfFnv"].items():
            cdf = qrsend.soliton_cdf(int(k_str))
            raw = b"".join(_struct.pack("<d", v) for v in cdf)
            self.assertEqual(fnv_hex(raw), expected, f"k={k_str} distribution drifted")

    def test_well_formed(self):
        for k in (1, 2, 17, 179, 716, 22000):
            cdf = qrsend.soliton_cdf(k)
            self.assertEqual(len(cdf), k)
            self.assertEqual(cdf[k - 1], 1.0, f"k={k} must terminate at exactly 1")
            self.assertGreater(cdf[0], 0, f"k={k} needs degree-1 mass or peeling never starts")
            for i in range(1, k):
                self.assertGreaterEqual(cdf[i], cdf[i - 1], f"k={k} not monotonic at {i}")


class TestFrameIndices(unittest.TestCase):
    def test_recorded_subsets(self):
        for k_str, by_seq in VECTORS["frameIndices"].items():
            k = int(k_str)
            cdf = qrsend.soliton_cdf(k)
            for seq_str, expected in by_seq.items():
                actual = qrsend.frame_indices(k, cdf, 4242, int(seq_str))
                self.assertEqual(actual, expected, f"k={k} seq={seq_str} subset changed")

    def test_bisect_matches_a_literal_transcription(self):
        # bisect_left runs in C and is what the port uses; this is the literal
        # translation of the JS loop. Fuzzing one against the other is what
        # licenses the substitution.
        import random
        rng = random.Random(20260806)
        for k in (2, 17, 179, 716, 4096):
            cdf = qrsend.soliton_cdf(k)
            for _ in range(20000):
                u = rng.random()
                lo, hi = 0, k - 1
                while lo < hi:
                    mid = (lo + hi) >> 1
                    if cdf[mid] >= u:
                        hi = mid
                    else:
                        lo = mid + 1
                literal = min(k, lo + 1)
                fast = min(k, min(__import__("bisect").bisect_left(cdf, u), k - 1) + 1)
                self.assertEqual(fast, literal, f"k={k} u={u!r}")

    def test_indices_are_distinct_and_in_range(self):
        for k in (1, 2, 17, 179, 4096):
            cdf = qrsend.soliton_cdf(k)
            for seq in range(2000):
                idx = qrsend.frame_indices(k, cdf, 9, seq)
                self.assertTrue(1 <= len(idx) <= k)
                self.assertEqual(len(set(idx)), len(idx), f"k={k} seq={seq} repeated an index")
                self.assertTrue(all(0 <= b < k for b in idx))


class TestEncoderStream(unittest.TestCase):
    def test_stream_fingerprints(self):
        # The end-to-end pin: dlog, the CDF, frame_seed, splitmix32,
        # frame_indices, the word padding and the XOR order, in one hash.
        for case, expected in VECTORS["streamFnv"].items():
            k, block_len, session_id = (int(x) for x in case.split("/"))
            encoder = qrsend.LTEncoder(test_payload(k * block_len - 7), block_len, session_id)
            self.assertEqual(encoder.k, expected["k"], f"{case} k changed")
            stream = b"".join(encoder.encode(seq) for seq in range(64))
            self.assertEqual(fnv_hex(stream), expected["fnv"], f"{case} stream changed")

    def test_every_frame_is_exactly_block_len(self):
        # The QR version is pinned off the first frame, so a short tail frame
        # would make every code after it the wrong size.
        block_len = 1445
        encoder = qrsend.LTEncoder(test_payload(block_len * 5 + 1), block_len, 3)
        self.assertEqual(encoder.k, 6)
        for seq in range(200):
            self.assertEqual(len(encoder.encode(seq)), block_len)


class TestContainer(unittest.TestCase):
    def test_frame_header_bytes(self):
        frame = qrsend.pack_frame(
            session_id=4242, seq=0x7FFFFFFF, k=179, block_len=16,
            total_len=2861, payload_fnv=0xDEADBEEF,
            block=bytes(range(1, 17)),
        )
        self.assertEqual(frame.hex(), VECTORS["frameBytes"])

    def test_uncompressed_container_is_byte_identical(self):
        v = VECTORS["container"]
        packed = qrsend.pack_file(v["name"], v["type"], bytes.fromhex(v["input"]))
        self.assertEqual(packed.compression, v["compression"])
        self.assertEqual(packed.container.hex(), v["bytes"])

    def test_gzip_decision_matches(self):
        # Only the DECISION is pinned, not the bytes: zlib and the browser's
        # CompressionStream legitimately emit different deflate streams for the
        # same input. The header fields and the payload round-trip are what the
        # receiver actually checks.
        v = VECTORS["gzipDecision"]
        data = bytes.fromhex(v["input"])
        packed = qrsend.pack_file("repeat.txt", "text/plain", data)
        self.assertEqual(packed.compression, v["compression"])
        self.assertEqual(packed.original_size, v["originalSize"])
        # Header minus the two length fields and the digest: magic, flag, and
        # the name/type lengths must agree exactly.
        self.assertEqual(packed.container[:9].hex(), v["headerBytes"][:18])
        self.assertEqual(packed.container[17:49].hex(), v["headerBytes"][34:98])
        body = packed.container[qrsend.FILE_HEADER_LEN:]
        body = body[len(b"repeat.txt") + len(b"text/plain"):]
        self.assertEqual(gzip.decompress(body), data)

    def test_below_threshold_is_never_gzipped(self):
        v = VECTORS["belowThreshold"]
        packed = qrsend.pack_file("small.txt", "text/plain", bytes.fromhex(v["input"]))
        self.assertEqual(packed.compression, v["compression"])

    def test_precompressed_types(self):
        for media, expected in [
            ("image/png", True), ("image/svg+xml", False), ("image/bmp", False),
            ("video/mp4", True), ("audio/wav", False), ("audio/mpeg", True),
            ("application/pdf", False), ("application/zip", True),
            ("application/epub+zip", True), ("text/plain", False),
            ("application/vnd.openxmlformats-officedocument.wordprocessingml.document", True),
            ("text/plain; charset=utf-8", False),
        ]:
            self.assertEqual(
                qrsend.is_precompressed_type(media), expected, f"{media} classified wrong"
            )


if __name__ == "__main__":
    unittest.main(verbosity=2)
